title: Moj Ahangar
position: Robotics Developer
affiliation: MetaOptima Technology Inc.
email:  mahangar@sfu.ca
keywords: Robotics
google_scholar: https://scholar.google.com/citations?user=eVubQIsAAAAJ&hl=en
github_link: https://github.com/Moj-Dev
linkedin: https://www.linkedin.com/in/mojtaba-ahangar-0bb326102/
avatar: ./assets/img/Mojtaba.png
google_analytics: UA-111540567-4
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.
canonical: https://minimal-light.yyliu.net/
remote_theme: PandaSekh/Jekyll-YAMT
